# Generated by Django 4.2.5 on 2023-09-25 06:35

import django.contrib.postgres.fields
from django.db import migrations, models
import e_learning.factories.base_model


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", e_learning.factories.base_model.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("heading", models.CharField(max_length=64)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            blank=True, default=None, null=True
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("teacher_id", models.CharField(max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="INR", max_length=20, null=True
                    ),
                ),
                ("max_seats", models.IntegerField(default=25, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("accepting_registrations", "Accepting Registrations"),
                            ("paused_registrations", "Paused Registrations"),
                            ("ended", "Ended"),
                        ],
                        default="inactive",
                        max_length=64,
                    ),
                ),
                (
                    "discount_currency",
                    models.CharField(
                        blank=True, default="INR", max_length=20, null=True
                    ),
                ),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=25, null=True),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "courses",
                "db_table": "courses",
            },
            managers=[
                ("objects", e_learning.factories.base_model.BaseManager()),
            ],
        ),
    ]
