# Generated by Django 4.2.5 on 2023-10-06 06:14

import __common__.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=200)),
                ("user_count", models.IntegerField(default=0, null=True)),
                ("file_url", models.CharField(blank=True, max_length=200, null=True)),
                ("segment_key", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", __common__.base_model.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=200)),
                ("product_count", models.IntegerField(default=0, null=True)),
                ("file_url", models.CharField(blank=True, max_length=200, null=True)),
                ("segment_key", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", __common__.base_model.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=200)),
                ("type", models.CharField(default="direct", max_length=64)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("inactive", "Inactive"), ("active", "Active")],
                        default="inactive",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                    ),
                ),
                (
                    "product_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.productsegment",
                    ),
                ),
                (
                    "user_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.usersegment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", __common__.base_model.BaseManager()),
            ],
        ),
    ]
