version: "3.7"
services:
  cache:
    image: redis
    ports:
      - "6379:6379"

  # worker:
  #   image: celery:latest
  #   command: ['celery', '-A', 'e_learning', 'worker', '--loglevel=info']
  #   depends_on:
  #     - cache

  # worker-monitor:
  #   image: mher/flower
  #   command: ['flower', '--broker=redis://localhost:6379', '--port=5555']
  #   ports:
  #     - 5557:5555
  #   depends_on:
  #     - cache