DEFAULT_CAROUSEL_GRID_LENGTH  = 2
DEFAULT_CAROUSEL_GRID_BREADTH = 2

SMALL_BANNER_LENGTH  = 200
MEDIUM_BANNER_LENGTH = 400
LARGE_BANNER_LENGTH  = 800
SMALL_BANNER_WIDTH   = 400
MEDIUM_BANNER_WIDTH  = 600
LARGE_BANNER_WIDTH   = 800

